apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 56.0.3
    chart: kube-prometheus-stack
    helm: 
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    automated: 
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
