# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   namespace: prometheus
#   name: nginx-ingress
#   labels:
#     service: nginx
# spec:
#   selector:
#     matchLabels:
#       app.kubernetes.io/component: controller
#       app.kubernetes.io/name: ingress-nginx 
#   namespaceSelector:
#     matchNames:
#     - ingress-nginx
#   endpoints:
#   - port: prometheus
#     interval: 5s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: prometheus
  name: nginx-ingress
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx-prometheus
      app.kubernetes.io/component: controller
  namespaceSelector:
    matchNames:
    - ingress-nginx
  endpoints:
  - port: prometheus
    path: /metrics
    interval: 5s