apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    #repoURL: https://github.com/argoproj/argocd-example-apps.git
    repoURL: https://github.com/TechwizsonORG/website-demo.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
# limit resource for this application argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
# limit ram cpu
  # resource:
  #  limits:
  #    cpu: "100m"
  #    memory: "128Mi"
  #  requests:
  #    cpu: "100m"
  #    memory: "128Mi"